#include <hal.h>

void boardInit(void) {
    palSetLineMode(BOARD_PAL_LINE_LED1, PAL_MODE_OUTPUT_PUSHPULL | PAL_STM32_OSPEED_HIGHEST);
    palSetLineMode(BOARD_PAL_LINE_LED2, PAL_MODE_OUTPUT_PUSHPULL | PAL_STM32_OSPEED_HIGHEST);
    palSetLineMode(BOARD_PAL_LINE_CAN_RX, PAL_MODE_ALTERNATE(9) | PAL_STM32_OSPEED_HIGHEST);
    palSetLineMode(BOARD_PAL_LINE_CAN_TX, PAL_MODE_ALTERNATE(9) | PAL_STM32_OSPEED_HIGHEST);
    palSetLineMode(BOARD_PAL_LINE_USART1_TX, PAL_MODE_ALTERNATE(7) | PAL_STM32_OSPEED_HIGHEST);
    palSetLineMode(BOARD_PAL_LINE_USART1_RX, PAL_MODE_ALTERNATE(7) | PAL_STM32_OSPEED_HIGHEST);


    palClearLine(BOARD_PAL_LINE_LED1);
    palClearLine(BOARD_PAL_LINE_LED2);
}
