#pragma once

#include <modules/platform_stm32h753/platform_stm32h753.h>

#define BOARD_CONFIG_HW_NAME "com.khaero.esc"
#define BOARD_CONFIG_HW_MAJOR_VER 0
#define BOARD_CONFIG_HW_MINOR_VER 1

#define BOARD_CONFIG_HW_INFO_STRUCTURE { \
    .hw_name = BOARD_CONFIG_HW_NAME, \
    .hw_major_version = BOARD_CONFIG_HW_MAJOR_VER, \
    .hw_minor_version = BOARD_CONFIG_HW_MINOR_VER, \
    .board_desc_fmt = SHARED_HW_INFO_BOARD_DESC_FMT_NONE, \
    .board_desc = 0, \
}

#define BOARD_FLASH_SIZE 2048

#define BOARD_PAL_LINE_USB_VBUS PAL_LINE(GPIOA, 9)
#define BOARD_PAL_LINE_USB_M PAL_LINE(GPIOA, 11)
#define BOARD_PAL_LINE_USB_P PAL_LINE(GPIOA, 12)

#define BOARD_PAL_LINE_SDMMC_D0 PAL_LINE(GPIOC, 8)
#define BOARD_PAL_LINE_SDMMC_D1 PAL_LINE(GPIOC, 9)
#define BOARD_PAL_LINE_SDMMC_D2 PAL_LINE(GPIOC, 10)
#define BOARD_PAL_LINE_SDMMC_D3 PAL_LINE(GPIOC, 11)
#define BOARD_PAL_LINE_SDMMC_CK PAL_LINE(GPIOC, 12)
#define BOARD_PAL_LINE_SDMMC_CMD PAL_LINE(GPIOD, 2)

#define BOARD_PAL_LINE_CAN1_RX PAL_LINE(GPIOB,8)
#define BOARD_PAL_LINE_CAN1_TX PAL_LINE(GPIOB,9)

#define BOARD_PAL_LINE_VBAT_H PAL_LINE(GPIOB,1) // 35 ADC12_INP5
#define BOARD_PAL_LINE_VBAT_L PAL_LINE(GPIOB,0) // 34 ADC12_INN5

#define BOARD_PAL_LINE_I1_H PAL_LINE(GPIOA,0) // 22 ADC1_INP16
#define BOARD_PAL_LINE_I1_L PAL_LINE(GPIOA,1) // 23 ADC1_INN16
#define BOARD_PAL_LINE_I2_H PAL_LINE(GPIOA,6) // 30 ADC12_INP3
#define BOARD_PAL_LINE_I2_L PAL_LINE(GPIOA,7) // 31 ADC12_INN3
#define BOARD_PAL_LINE_I3_H PAL_LINE(GPIOC,3) // 18 ADC3_INP1
#define BOARD_PAL_LINE_I3_L PAL_LINE(GPIOC,2) // 17 ADC3_INN1

#define BOARD_PAL_LINE_V1_H PAL_LINE(GPIOA,4) // 28 ADC12_INP18
#define BOARD_PAL_LINE_V1_L PAL_LINE(GPIOA,5) // 29 ADC12_INN18
#define BOARD_PAL_LINE_V2_H PAL_LINE(GPIOC,4) // 32 ADC12_INP4
#define BOARD_PAL_LINE_V2_L PAL_LINE(GPIOC,5) // 33 ADC12_INN4
#define BOARD_PAL_LINE_V3_H PAL_LINE(GPIOC,0) // 15 ADC123_INP10
#define BOARD_PAL_LINE_V3_L PAL_LINE(GPIOC,1) // 16 ADC123_INN10

#define BOARD_PAL_LINE_PH1_H PAL_LINE(GPIOE,9) // 39 TIM1_CH1
#define BOARD_PAL_LINE_PH1_L PAL_LINE(GPIOE,8) // 38 TIM1_CH1N
#define BOARD_PAL_LINE_PH2_H PAL_LINE(GPIOE,11) // 41 TIM1_CH2
#define BOARD_PAL_LINE_PH2_L PAL_LINE(GPIOE,10) // 40 TIM1_CH2N
#define BOARD_PAL_LINE_PH3_H PAL_LINE(GPIOE,13) // 43 TIM1_CH3
#define BOARD_PAL_LINE_PH3_L PAL_LINE(GPIOE,12) // 42 TIM1_CH3N

// Worker thread debug pins
#define BOARD_PAL_LINE_ADC_DEBUG_PIN PAL_LINE(GPIOA,15)
#define BOARD_PAL_LINE_WORKER_LPWORK PAL_LINE(GPIOC,11)
#define BOARD_PAL_LINE_WORKER_SLCAN PAL_LINE(GPIOD,0)
#define BOARD_PAL_LINE_WORKER_CAN PAL_LINE(GPIOD,2)
#define BOARD_PAL_LINE_WORKER_HPWORK PAL_LINE(GPIOD,4)
#define BOARD_PAL_LINE_DBG1 PAL_LINE(GPIOB,3)
#define BOARD_PAL_LINE_PWM_DEBUG PAL_LINE(GPIOB,5)

#define ADC_CH_VBAT 5

#define ADC_CH_I1 16
#define ADC_CH_I2 3
#define ADC_CH_I3 1

#define ADC_CH_V1 18
#define ADC_CH_V2 4
#define ADC_CH_V3 10

#define ADC_CH_VREFINT 19
#define ADC_CH_VSENSE 18

#define VREFINT_CAL (*((uint16_t*)0x1FF1E860))
#define TS_CAL1_TEMP 30.0
#define TS_CAL2_TEMP 110.0
#define TS_CAL1 (*((uint16_t*)0x1FF1E820))
#define TS_CAL2 (*((uint16_t*)0x1FF1E840))

#define HAL_USE_PWM TRUE
#define STM32_PWM_USE_ADVANCED TRUE

#if !defined(__ASSEMBLER__) && !defined(TARGET_BOOTLOADER) && defined(MODULE_INVERTER_ENABLED)
#include <modules/inverter/inverter.h>

#define BOARD_NUM_INVERTERS 1

// this is done with define so that #ifdef(INVD1) works
#define INVD _inverters
#define INVD1 _inverters[0]
extern Inverter _inverters[];

#define INVD1_PHASE_CURRENT_SENSITIVITY -0.005
#define INVD1_PHASE_VOLTAGE_SENSITIVITY 0.02922046403
#define INVD1_BUS_VOLTAGE_SENSITIVITY 0.02922164172
#endif
