#pragma once

#include <stddef.h>
#include <stdbool.h>

// Logger public API
//
// Use logger_write() for raw binary records. The logger module handles queuing
// via pubsub, file rotation, and free-space management.
//
// Filenames are created under LOGGER_BASE_DIR (default: "/LOGS") as:
//   <prefix>_<index>.<suffix>
// where <index> is an auto-incrementing positive integer (starting at 1).
//
// Constraints:
// - prefix: up to 8 characters (8.3 filename compatibility)
// - suffix: up to 3 characters (no leading dot)
//
// The write is enqueued; data is copied into an internal message buffer.
void logger_write(const char* fileprefix, const char* filesuffix, const void* data, size_t data_len);

// ISR-safe, non-blocking variant using pubsub_try_publish_message_I.
// Returns false if it could not enqueue.
bool logger_write_I(const char* fileprefix, const char* filesuffix, const void* data, size_t data_len);

// ArduPilot-like logging API.
// When a message name is first seen per logfile, a "FMT" descriptor record is
// automatically written describing the format and labels. Subsequent calls just
// write the payload encoded according to the format string.
//
// name: 1-4 ASCII chars identifying the message (padded with NULs as needed)
// format: format letters similar to AP_Logger (subset supported):
//   b:int8  B:uint8  h:int16  H:uint16  i:int32  I:uint32
//   q:int64 Q:uint64 f:float d:double  L:uint32 (alias for TimeUS)
// labels: comma-separated column names (e.g. "TimeUS,Roll,Pitch")
void logger_write_ap(const char* fileprefix,
			  const char* filesuffix,
			  const char* name,
			  const char* format,
			  const char* labels,
			  ...);

// ISR-safe, non-blocking variant using pubsub_try_publish_message_I.
// Returns false if it could not enqueue.
// Note: FMT records are not automatically generated in ISR context -
// they must be pre-generated by calling logger_write_ap() first.
bool logger_write_ap_I(const char* fileprefix,
			      const char* filesuffix,
			      const char* name,
			      const char* format,
			      ...);

// Generate FMT record in ISR context.
// This should be called during ISR to ensure proper log format definition.
bool logger_generate_fmt_I(const char* fileprefix,
			      const char* filesuffix,
			      const char* name,
			      const char* format,
			      const char* labels);

// Optional configuration macros (override in framework_conf.h):
//   #define LOGGER_WORKER_THREAD           my_worker_thread
//   #define LOGGER_PUBSUB_TOPIC_GROUP      my_topic_group
//   #define LOGGER_BASE_DIR                "/LOGS"
//   #define LOGGER_ROTATE_BYTES            (1024*1024)
//   #define LOGGER_MIN_FREE_BYTES          (8*1024*1024)
//   #define LOGGER_MAX_PREFIX_LEN          8
//   #define LOGGER_MAX_SUFFIX_LEN          3

