LOGGER_MODULE_DIR := $(patsubst %/,%,$(dir $(lastword $(MAKEFILE_LIST))))

# Ensure FATFS/SD support via uSD module
MODULES_ENABLED += uSD

USE_PROCESS_STACKSIZE = 4096
USE_EXCEPTIONS_STACKSIZE = 4096
